from graphviz import Digraph
import os

def create_main_architecture():
    dot = Digraph(comment='Shoplifting Detection System Architecture')
    dot.attr(rankdir='TB')
    dot.attr('node', shape='box', style='rounded')
    dot.node('A', 'Raw Video Data\n(MP4/AVI)')
    dot.node('B', 'Data Preparation\n(1_prepare_data.py)')
    dot.node('C', 'Frame Extraction\n(30 frames/video)')
    dot.node('D', 'Dataset Creation')
    dot.node('E', 'Training Data\n(80%)')
    dot.node('F', 'Validation Data\n(20%)')
    dot.node('G', 'Model Training\n(2_train_model.py)')
    dot.node('H', 'YOLOv8 Model')
    dot.node('H_caption', 'YOLOv8: Fine-tuned classifier\n(Normal vs Shoplifting)\nUsed for training & inference', shape='note', fontsize='10')
    dot.node('I', 'Testing Pipeline')
    dot.node('J', 'Pretrained Test\n(3_test_pretrained.py)')
    dot.node('K', 'Custom Test\n(4_test_custom.py)')
    dot.node('L', 'Results & Analytics')
    dot.edge('A', 'B')
    dot.edge('B', 'C')
    dot.edge('C', 'D')
    dot.edge('D', 'E')
    dot.edge('D', 'F')
    dot.edge('E', 'G')
    dot.edge('F', 'G')
    dot.edge('G', 'H')
    dot.edge('H', 'I')
    dot.edge('I', 'J')
    dot.edge('I', 'K')
    dot.edge('J', 'L')
    dot.edge('K', 'L')
    dot.edge('H', 'H_caption', style='dashed', arrowhead='none')
    dot.render('architecture/main_architecture', format='png', cleanup=True)

def create_data_preparation_diagram():
    dot = Digraph(comment='Data Preparation Pipeline')
    dot.attr(rankdir='LR')
    dot.attr('node', shape='box', style='rounded')
    dot.node('A', 'Input Videos')
    dot.node('B', 'Frame Extractor')
    dot.node('C', 'Train-Val Splitter')
    with dot.subgraph(name='cluster_0') as c:
        c.attr(label='Dataset Structure')
        c.node('D1', 'Train/Normal')
        c.node('D2', 'Train/Shoplifting')
        c.node('D3', 'Val/Normal')
        c.node('D4', 'Val/Shoplifting')
    dot.edge('A', 'B')
    dot.edge('B', 'C')
    dot.edge('C', 'D1')
    dot.edge('C', 'D2')
    dot.edge('C', 'D3')
    dot.edge('C', 'D4')
    dot.render('architecture/data_preparation', format='png', cleanup=True)

def create_model_training_diagram():
    dot = Digraph(comment='Model Training Pipeline')
    dot.attr(rankdir='TB')
    dot.attr('node', shape='box', style='rounded')
    dot.node('A', 'YOLOv8-cls Pretrained')
    dot.node('B', 'Training Process')
    with dot.subgraph(name='cluster_0') as c:
        c.attr(label='Training Configuration')
        c.node('C1', 'Image Size: 224x224')
        c.node('C2', 'Batch Size: 16')
        c.node('C3', 'Epochs: 10')
        c.node('C4', 'Patience: 10')
    dot.node('D', 'Training Loop')
    dot.node('E', 'Best Model Selection')
    dot.node('F', 'Model Saving')
    dot.node('A_caption', 'YOLOv8 (pretrained) provides learned features\nFine-tuned on the shoplifting dataset to produce a classifier', shape='note', fontsize='10')
    dot.edge('A', 'B')
    dot.edge('B', 'C1')
    dot.edge('B', 'C2')
    dot.edge('B', 'C3')
    dot.edge('B', 'C4')
    dot.edge('C1', 'D')
    dot.edge('C2', 'D')
    dot.edge('C3', 'D')
    dot.edge('C4', 'D')
    dot.edge('D', 'E')
    dot.edge('E', 'F')
    dot.edge('A', 'A_caption', style='dashed', arrowhead='none')
    dot.render('architecture/model_training', format='png', cleanup=True)

def create_testing_pipeline_diagram():
    dot = Digraph(comment='Testing Pipeline')
    dot.attr(rankdir='TB')
    dot.attr('node', shape='box', style='rounded')
    dot.node('A', 'Video Input')
    dot.node('B', 'Frame Processing')
    dot.node('C', 'Model Inference')
    with dot.subgraph(name='cluster_0') as c:
        c.attr(label='Results Processing')
        c.node('D1', 'Classification')
        c.node('D2', 'Confidence Score')
        c.node('D3', 'Visual Feedback')
    dot.node('E', 'Performance Analytics')
    dot.node('F', 'Output Video')
    dot.node('C_caption', 'Per-frame inference → class probabilities\nTop class + confidence used for annotation and analytics', shape='note', fontsize='10')
    dot.edge('A', 'B')
    dot.edge('B', 'C')
    dot.edge('C', 'D1')
    dot.edge('C', 'D2')
    dot.edge('C', 'D3')
    dot.edge('D1', 'E')
    dot.edge('D2', 'E')
    dot.edge('D3', 'F')
    dot.edge('C', 'C_caption', style='dashed', arrowhead='none')
    dot.render('architecture/testing_pipeline', format='png', cleanup=True)

def verify_graphviz():
    import shutil
    if not shutil.which('dot'):
        print("ERROR: Graphviz is not found in PATH!")
        print("\nPlease ensure:")
        print("1. Graphviz is installed (you can install it using 'winget install graphviz')")
        print("2. Add Graphviz to PATH:")
        print("   - Usually located at: C:\\Program Files\\Graphviz\\bin")
        print("   - Add this path to your system's PATH environment variable")
        print("\nAfter installing, you may need to restart your terminal/VS Code")
        return False
    return True

def main():
    if not verify_graphviz():
        return
    os.makedirs('architecture', exist_ok=True)
    print("Generating architecture diagrams...")
    create_main_architecture()
    create_data_preparation_diagram()
    create_model_training_diagram()
    create_testing_pipeline_diagram()
    print("Architecture diagrams have been generated in the 'architecture' folder:")
    print("1. main_architecture.png - Overall system architecture")
    print("2. data_preparation.png - Data preparation pipeline")
    print("3. model_training.png - Model training pipeline")
    print("4. testing_pipeline.png - Testing pipeline")

if __name__ == "__main__":
    main()
