# YOLO Unauthorized Person Detection System Configuration
model:
  yolo_model_path: "yolov8n.pt"
  detection_confidence: 0.5
  face_tolerance: 0.5
  max_faces_per_frame: 10

camera:
  camera_index: 0
  frame_width: 640
  frame_height: 480
  fps: 30

paths:
  authorized_faces_dir: "dataset/authorized_faces"
  test_images_dir: "dataset/test_images"
  logs_dir: "logs"
  models_dir: "models"
  embeddings_file: "dataset/face_embeddings.npy"
  authorized_persons_file: "dataset/authorized_persons.json"

alerts:
  enable_sound: true
  enable_email: false
  enable_sms: false
  alert_cooldown: 30
  alert_sound_path: "alert_system/alert.wav"

email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  sender_email: "your_email@gmail.com"
  sender_password: "your_app_password"
  recipient_email: "admin@yourcompany.com"

api:
  host: "0.0.0.0"
  port: 8000
  enable_cors: true

logging:
  log_level: "INFO"
  log_file: "logs/detection.log"
  enable_console_log: true

display:
  show_confidence: true
  show_fps: true
  font_scale: 0.7
  font_thickness: 2
  colors:
    authorized: [0, 255, 0]
    unauthorized: [0, 0, 255]
    text: [255, 255, 255]

performance:
  use_gpu: true
  num_threads: 4
  frame_skip: 1